arch: 
     - arm64
     - amd64
language: python
python:
  - "nightly"
  - 3.6
  - 3.5
  - 3.4
  - 2.7
sudo: false
install:
  - pip install --upgrade pip
  - pip install .
  - pip install --pre --upgrade traitlets[test] pytest pytest-cov codecov
  - test -z ${TEST_DEPS} || pip install --upgrade ${TEST_DEPS}
  - pip freeze

script:
  - ${TEST:-py.test --cov traitlets -v traitlets}
after_success:
  - codecov
matrix:
  allow_failures:
    - python: "nightly"
  include:
    - arch: 
          - arm64
          - amd64
      python: 3.6
      env:
        - TEST_DEPS=ipython[test]
        - TEST=iptest
    - arch: 
          - arm64
          - amd64
      python: 3.6
      env:
        - TEST_DEPS=git+https://github.com/jupyter/nbconvert.git#egg=nbconvert[test]
        - TEST="py.test --pyargs nbconvert"
    - arch: 
          - arm64
          - amd64 
      python: 3.6
      env:
        - TEST_DEPS=notebook[test]
        - TEST="nosetests --exclude selenium notebook"
    - arch: 
          - arm64
          - amd64 
      python: 3.6
      env:
        - TEST_DEPS=ipywidgets[test]
        - TEST="pytest --pyargs ipywidgets"
    - arch: 
          - arm64
          - amd64
     python: 3.6
     env:
        - TEST_DEPS=traittypes[test]
        - TEST="nosetests traittypes"
   
